%% This file show the illustration of the dependence of bias and variance on model complexity, governed by a regularization parameter lambda.
% using random value to train, and use fixed value of x to test(in order to compute average of 100 fit)
% using ln(lambda) = -10:1:0 to see the influence of lambda

% N is the size of dataset and M is order of polynomial
N = 25;
M = 7;
lambda_original = -10:1:4;
lambda = exp(lambda_original);

t = zeros(N,100); % t is target value produced by y = sin(2*pi*x) + gaussian noise
x = zeros(N,100); % x is randomly generated 100 datasets that each of which consists of 25 points
x_test = (0.04:0.04:1)';% x_test is fixed datasets consists of 25 points to test the performance of model
f_x = zeros(N,100);% f_x is output of the model when using x_test 
f_x_sum = zeros(N,1);% in order to compute the average of 100 dataset, we need use f_x_sum to sum all the f_x of 100 dataset
w = zeros(M,1);% w is the model generated by x ,t and fai
fai = zeros(N,M);% fai is design matrix of x
fai_test = zeros(N,M);% fai_test is design matrix of x_test
figure(1);
for k = 1:1:length(lambda)
    figure(k);
    for i = 1:1:100
        x(:,i) = sort(randi(100,N,1)/100);  % randomly generate x
        for j = 1:1:M+1                     % compute fai and fai_test
            fai(:,j) = power(x(:,i),j-1);
            fai_test(:,j) = power(x_test,j-1);
        end
        t(:,i) = sin(2*pi*x(:,i))+sqrt(0.4)*randn(N,1);% compute target value
        temp = inv(lambda(k)*eye(M+1) + fai'*fai);
        w = temp*fai'*t(:,i);                    % compute the model
        f_x(:,i) = fai_test*w;                   % compute the f_x
        subplot(1,2,1);
        title(strcat('ln(lambda)=',num2str(lambda_original(k))));
        plot(x_test,f_x(:,i),'r');
        hold on;
    end
    subplot(1,2,2);    
    f_x_mean = mean(f_x,2);  % compute the average of 100 fit
    t_test = sin(2*pi*x_test);
    bias_2 = mean((f_x_mean - t_test).^2);
    vari
    plot(x_test,f_x_mean,'r');
    hold on;
    plot(x_test,t_test,'g');
    title('Average of 100 fit');
end
